In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [2]:
DATA_URL = 'https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz'

path = tf.keras.utils.get_file('mnist.npz', DATA_URL)
with np.load(path) as data:
  train_examples = data['x_train']
  train_labels = data['y_train']
  test_examples = data['x_test']
  test_labels = data['y_test']

In [3]:
with np.load(path) as data:
    print(data['x_train'].shape)

(60000, 28, 28)


In [10]:
with np.load(path) as data:
    print(data['x_train'])

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [4]:
train_dataset = tf.data.Dataset.from_tensor_slices((train_examples, train_labels))
test_dataset = tf.data.Dataset.from_tensor_slices((test_examples, test_labels))

In [5]:
BATCH_SIZE = 64
SHUFFLE_BUFFER_SIZE = 100

train_dataset = train_dataset.shuffle(SHUFFLE_BUFFER_SIZE).batch(BATCH_SIZE)
test_dataset = test_dataset.batch(BATCH_SIZE)

In [6]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10)
])

model.compile(optimizer=tf.keras.optimizers.RMSprop(),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['sparse_categorical_accuracy'])

In [7]:
model.fit(train_dataset, epochs=10)

Epoch 1/10
938/938 [==============================] - 3s 1ms/step - loss: 2.7651 - sparse_categorical_accuracy: 0.8693
Epoch 2/10
938/938 [==============================] - 1s 1ms/step - loss: 0.5036 - sparse_categorical_accuracy: 0.9261
Epoch 3/10
938/938 [==============================] - 1s 1ms/step - loss: 0.3775 - sparse_categorical_accuracy: 0.9434
Epoch 4/10
938/938 [==============================] - 1s 1ms/step - loss: 0.3375 - sparse_categorical_accuracy: 0.9526
Epoch 5/10
938/938 [==============================] - 1s 1ms/step - loss: 0.2964 - sparse_categorical_accuracy: 0.9569
Epoch 6/10
938/938 [==============================] - 1s 1ms/step - loss: 0.2576 - sparse_categorical_accuracy: 0.9629
Epoch 7/10
938/938 [==============================] - 1s 1ms/step - loss: 0.2504 - sparse_categorical_accuracy: 0.9657
Epoch 8/10
938/938 [==============================] - 1s 1ms/step - loss: 0.2351 - sparse_categorical_accuracy: 0.9687
Epoch 9/10
938/938 [============================

In [8]:
model.evaluate(test_dataset)

157/157 [==============================] - 0s 1ms/step - loss: 0.8597 - sparse_categorical_accuracy: 0.9479


[0.8596543073654175, 0.9478999972343445]