In [28]:
import h5py
import datetime as dt
import cv2
import numpy as np
import os
import fnmatch
import matplotlib.pyplot as plt
import matplotlib.image as img
from PIL import Image

In [17]:
f = h5py.File('trainingsetv1d0.h5', 'r')

print(f['1080Lines']['test']['0Lojrrjlme'].keys())

<KeysViewHDF5 ['0.5.png', '1.0.png', '2.0.png', '4.0.png']>


In [9]:
f['1080Lines']['test']['0Lojrrjlme']['0.5.png']

<HDF5 dataset "0.5.png": shape (1, 140, 170), type "<f4">

In [10]:
f = h5py.File('trainingsetv1d0.h5', 'r')

for key in f.keys():
    print(f[key].name)
    print(f[key])

/1080Lines
<HDF5 group "/1080Lines" (3 members)>
/1400Ripples
<HDF5 group "/1400Ripples" (3 members)>
/Air_Compressor
<HDF5 group "/Air_Compressor" (3 members)>
/Blip
<HDF5 group "/Blip" (3 members)>
/Chirp
<HDF5 group "/Chirp" (3 members)>
/Extremely_Loud
<HDF5 group "/Extremely_Loud" (3 members)>
/Helix
<HDF5 group "/Helix" (3 members)>
/Koi_Fish
<HDF5 group "/Koi_Fish" (3 members)>
/Light_Modulation
<HDF5 group "/Light_Modulation" (3 members)>
/Low_Frequency_Burst
<HDF5 group "/Low_Frequency_Burst" (3 members)>
/Low_Frequency_Lines
<HDF5 group "/Low_Frequency_Lines" (3 members)>
/No_Glitch
<HDF5 group "/No_Glitch" (3 members)>
/None_of_the_Above
<HDF5 group "/None_of_the_Above" (3 members)>
/Paired_Doves
<HDF5 group "/Paired_Doves" (3 members)>
/Power_Line
<HDF5 group "/Power_Line" (3 members)>
/Repeating_Blips
<HDF5 group "/Repeating_Blips" (3 members)>
/Scattered_Light
<HDF5 group "/Scattered_Light" (3 members)>
/Scratchy
<HDF5 group "/Scratchy" (3 members)>
/Tomte
<HDF5 group "/T

In [22]:
# for key in f['1080Lines']['test']['0Lojrrjlme'].keys():
#     print(f['1080Lines']['test']['0Lojrrjlme'][key])
#     print(f['1080Lines']['test']['0Lojrrjlme'][key])
# print(f.keys())
# print(f['1080Lines']['train'].keys())
# print(f['1080Lines']['test'])
# print(f['1080Lines']['validation'])
a = np.array(f['1080Lines']['test']['0Lojrrjlme']['0.5.png'][0])
print(a)
# print(a[0])
# print(type(a[0,0,0]))
# print(f['1080Lines']['test'].keys())

[[0.13733548 0.12756088 0.12923469 ... 0.12544493 0.11392944 0.12916133]
 [0.13152261 0.10703795 0.09600375 ... 0.14972022 0.09473844 0.09722944]
 [0.08483434 0.10654609 0.13528761 ... 0.12482796 0.08985194 0.10106625]
 ...
 [0.1520418  0.15337974 0.15550873 ... 0.10262123 0.10057538 0.10216707]
 [0.14577287 0.1484211  0.14900266 ... 0.09640902 0.09640902 0.09640902]
 [0.09859176 0.10078784 0.10171518 ... 0.09877075 0.0992262  0.0992262 ]]


In [30]:
# Normalize array into 255
a *= (255.0/a.max())

In [38]:
img = Image.fromarray(a)
img.show()

In [14]:
# np.savetxt('filename',a[0])

In [90]:
a = np.array(f['1080Lines']['test']['0Lojrrjlme']['0.5.png'])
a = a.flatten()
print(len(a))

23800


In [98]:
a = np.zeros((3,22,1,3))
# print(a)
# print(a[0][0])
# print(np.array([1]))
# print(a)
# print(a)
# print(type(a[0][0]))

range(len(a[0][0][0]))

range(0, 3)